//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalMiniso.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTAS
    {
        public int ID { get; set; }
        public int TENDER_ID { get; set; }
        public string TENDER_NAME { get; set; }
        public string TENDER_DESC { get; set; }
        public string TENDER_TYPE_CODE { get; set; }
        public decimal MIN_UNIT_AMOUNT { get; set; }
        public int COUNTABLE_FLG { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string CARD_SCHEME { get; set; }
        public string CERT_TYPE_NO { get; set; }
        public string ACOUNT { get; set; }
    }
}
