//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalMiniso.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV
    {
        public int ID { get; set; }
        public Nullable<int> DocNum { get; set; }
        public string LineNum { get; set; }
        public string ItemCode { get; set; }
        public string Quantity { get; set; }
        public string Price { get; set; }
        public string Currency { get; set; }
        public string Rate { get; set; }
        public string U_MNSO_ValorDsco { get; set; }
        public string WhsCode { get; set; }
        public string CodeBars { get; set; }
        public string TaxCode { get; set; }
        public string LineTotal { get; set; }
        public string PriceBefDi { get; set; }
        public string OcrCode { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public string NCMCode { get; set; }
        public string UomCode { get; set; }
        public string U_tipoOpT12 { get; set; }
        public string U_BPP_OPER { get; set; }
        public string U_BPP_SUJETORENTA { get; set; }
        public string TaxOnly { get; set; }
    
        public virtual OINV OINV { get; set; }
    }
}
