//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalMiniso.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV2
    {
        public int ID { get; set; }
        public string DocNum { get; set; }
        public string LineNum { get; set; }
        public string ExpnsCode { get; set; }
        public string LineTotal { get; set; }
        public string TaxCode { get; set; }
        public string campo { get; set; }
        public string SKU { get; set; }
    }
}
