//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalMiniso.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OINV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OINV()
        {
            this.INV = new HashSet<INV>();
            this.RCT = new HashSet<RCT>();
        }
    
        public int DocNum { get; set; }
        public string DocEntry { get; set; }
        public string DocType { get; set; }
        public string DocDate { get; set; }
        public string TaxDate { get; set; }
        public string DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string DocCur { get; set; }
        public string DocRate { get; set; }
        public string LicTradNum { get; set; }
        public string comments { get; set; }
        public string DocSubType { get; set; }
        public string NumAtCard { get; set; }
        public string U_BPP_OPER { get; set; }
        public string U_BPP_MDTD { get; set; }
        public string U_BPV_SERI { get; set; }
        public string U_BPV_NCON2 { get; set; }
        public string U_BPP_MDSD { get; set; }
        public string U_BPP_MDCD { get; set; }
        public string U_BPP_TDOCORG { get; set; }
        public string U_BPP_MDTO { get; set; }
        public string U_BPP_MDSO { get; set; }
        public string U_BPP_MDCO { get; set; }
        public string U_BPP_SDOCTOTAL { get; set; }
        public string U_BPP_SDOCDATE { get; set; }
        public string U_BPP_SDOCTC { get; set; }
        public string U_APTOS_TPO_DOCTO { get; set; }
        public string U_APTOS_FOLIO_ENICO { get; set; }
        public string U_APTOS_FECHAEMISION { get; set; }
        public string U_APTOS_HORAEMISION { get; set; }
        public string U_APTOS_COD_VENDEDOR { get; set; }
        public string U_APTOS_NUM_TERMINAL { get; set; }
        public string U_APTOS_MOTIVOCANCELA { get; set; }
        public string DocTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV> INV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCT> RCT { get; set; }
    }
}
