//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalMiniso.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPM
    {
        public int ID { get; set; }
        public Nullable<int> DocNum1 { get; set; }
        public string DoCNum { get; set; }
        public string LineNum { get; set; }
        public string DocEntry { get; set; }
        public string SumApplied { get; set; }
        public string InvType { get; set; }
    
        public virtual ORIN ORIN { get; set; }
    }
}
